import { PrismaClient } from '@prisma/client';

const IMG = {
  rudraksha: 'https://images.unsplash.com/photo-1622993361118-b6365d859ab6?w=400&h=400&fit=crop',
  crystal: 'https://images.unsplash.com/photo-1584157234994-b1ea5fc1b444?w=400&h=400&fit=crop',
  brassDiya: 'https://images.unsplash.com/photo-1702505433756-88130191bb4b?w=400&h=400&fit=crop',
  brassIdol: 'https://images.unsplash.com/photo-1508133111629-be3f6e535a52?w=400&h=400&fit=crop',
  pujaThali: 'https://images.unsplash.com/photo-1761295908789-42feef309297?w=400&h=400&fit=crop',
  sandalwood: 'https://images.unsplash.com/photo-1740819912830-d696b4de3fa8?w=400&h=400&fit=crop',
  gheelamp: 'https://images.unsplash.com/photo-1767693807049-5b624e6116cc?w=400&h=400&fit=crop',
  roseQuartz: 'https://images.unsplash.com/photo-1665378764540-8aca31360df9?w=400&h=400&fit=crop',
  blackStone: 'https://images.unsplash.com/photo-1753522312806-a78c9fee860e?w=400&h=400&fit=crop',
  incense: 'https://images.unsplash.com/photo-1663075039782-59a2330a2ec1?w=400&h=400&fit=crop',
  diwaliLamps: 'https://images.unsplash.com/photo-1740847145862-85f296386a2b?w=400&h=400&fit=crop',
  pujaCeremony: 'https://images.unsplash.com/photo-1761471658187-26030cf2be8c?w=400&h=400&fit=crop',
  ganesh: 'https://images.unsplash.com/photo-1760283809688-d105d141ad64?w=400&h=400&fit=crop',
};

const products = [
  // Best Sellers
  { title: 'Silver Capping Karungali Combo', price: 949.0, originalPrice: 1499.0, category: 'bestsellers', image: IMG.sandalwood, badge: 'Best Seller', description: 'Handpicked Karungali (Ebony) wood beads individually capped with 92.5% sterling silver, giving each bead a premium, lustrous finish. Karungali is revered in South Indian tradition for its protective energy and its ability to ward off negative vibrations. Ideal for daily japa practice or worn as a sacred bracelet.' },
  { title: 'Brass Peacock Diya with Stand', price: 1299.0, originalPrice: 1999.0, category: 'bestsellers', image: IMG.brassDiya, badge: 'Best Seller', description: 'Cast from solid brass using the traditional lost-wax method, this peacock diya stands 8 inches tall and holds pure ghee or oil. The intricate feather detailing is hand-finished by master artisans in Moradabad. A timeless piece for your puja altar that becomes more beautiful as the brass develops its natural patina over time.' },
  { title: 'Rudraksha Mala 108 Beads', price: 799.0, originalPrice: 1299.0, category: 'bestsellers', image: IMG.rudraksha, badge: 'Best Seller', description: 'A full 108-bead mala strung from authentic 5 Mukhi Rudraksha sourced from the foothills of Nepal. Each bead is lab-tested for genuineness and carries natural, unaltered mukhi (clefts). 5 Mukhi Rudraksha is associated with Lord Shiva and is believed to promote calmness, focus, and freedom from negative karma. String: silk thread with a copper guru bead.' },
  { title: 'Crystal Shree Yantra', price: 2499.0, originalPrice: 3999.0, category: 'bestsellers', image: IMG.crystal, badge: 'Best Seller', description: 'Meticulously hand-carved from a single block of natural clear quartz crystal, this Shree Yantra represents the sacred geometry of Goddess Lakshmi. Placing it facing east in your home or office is said to attract prosperity, success, and positive energy. Each piece is unique and comes energised with Vedic mantras by our in-house pandit.' },

  // Healing & Vastu - Our Combos
  { title: 'Vastu Pyramid Combo Set', price: 1499.0, originalPrice: 2299.0, category: 'healing-combos', image: IMG.pujaCeremony, badge: null, description: 'A complete Vastu correction kit containing 9 copper pyramids, 1 brass Vastu Purush plate, and a guidebook explaining placement for each cardinal direction. Copper pyramids amplify positive earth energy and are traditionally used to neutralise geopathic stress in homes and offices. Handmade in India.' },
  { title: 'Crystal Healing Kit', price: 1799.0, originalPrice: 2499.0, category: 'healing-combos', image: IMG.roseQuartz, badge: null, description: 'A curated set of 7 tumbled healing crystals — one for each chakra — including Amethyst (Crown), Lapis Lazuli (Third Eye), Sodalite (Throat), Rose Quartz (Heart), Citrine (Solar Plexus), Carnelian (Sacral), and Red Jasper (Root). Comes with an organza pouch and a fold-out crystal properties card.' },
  { title: 'Feng Shui Energy Kit', price: 1299.0, originalPrice: 1899.0, category: 'healing-combos', image: IMG.crystal, badge: null, description: 'Brings the principles of Feng Shui into your living space with this thoughtfully assembled kit. Includes a crystal money tree, a pair of brass Fu Dogs, Bamboo Lucky Plant seeds, and a placement guide. Together these items are believed to channel wealth, protection, and harmony into the home.' },
  { title: 'Chakra Balancing Set', price: 2199.0, originalPrice: 3499.0, category: 'healing-combos', image: IMG.blackStone, badge: null, description: 'A premium chakra balancing collection featuring 7 raw crystal wands, a black tourmaline grounding stone, a selenite wand for cleansing, and a double-terminated clear quartz point. Each crystal is natural, unpolished and sourced ethically. Includes a full-colour chakra map and meditation instructions.' },

  // Healing & Vastu - Yantra & Plates
  { title: 'Brass Shree Yantra Plate', price: 899.0, originalPrice: 1499.0, category: 'healing-yantra', image: IMG.brassDiya, badge: null, description: 'A finely engraved Shree Yantra on a thick 3mm brass plate, treated with an anti-tarnish coating to preserve its golden sheen. Measures 6×6 inches. Traditionally placed on the puja altar or in the north-east corner (Ishan kona) of the home to attract abundance and divine blessings from Goddess Lakshmi.' },
  { title: 'Kuber Yantra Copper', price: 599.0, originalPrice: 999.0, category: 'healing-yantra', image: IMG.diwaliLamps, badge: null, description: 'Laser-etched on pure copper for precision and longevity, this Kuber Yantra is dedicated to Lord Kuber, the celestial treasurer. It is believed to remove financial obstacles and open new streams of income when placed in the north direction of the main living area. Dimensions: 4×4 inches.' },
  { title: 'Navgraha Yantra Set', price: 1599.0, originalPrice: 2499.0, category: 'healing-yantra', image: IMG.pujaCeremony, badge: null, description: 'A complete set of 9 individual yantra plates — one for each of the Navagrahas (Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, Ketu). Each plate is engraved on copper and comes in a velvet-lined wooden box. Performing planetary remedies using these yantras is believed to reduce malefic effects in one\'s horoscope.' },
  { title: 'Maha Mrityunjaya Yantra', price: 799.0, originalPrice: 1299.0, category: 'healing-yantra', image: IMG.pujaThali, badge: null, description: 'Engraved on pure copper, this powerful yantra is dedicated to Lord Shiva in his Mritunjaya form — the conqueror of death and disease. Chanting the Maha Mrityunjaya mantra while facing this yantra is said to provide protection from illness, accidents, and untimely death. Size: 5×5 inches.' },

  // Healing & Vastu - Healing Gifts
  { title: 'Selenite Charging Plate', price: 699.0, originalPrice: 1099.0, category: 'healing-gifts', image: IMG.crystal, badge: null, description: 'A smooth, oval selenite plate (approx 15cm × 10cm) that continuously self-cleanses and recharges any crystals placed on it. Selenite vibrates at one of the highest frequencies of any crystal and never needs cleansing itself. A perfect gift for anyone who works with healing stones. Handle with care as selenite is a naturally soft mineral.' },
  { title: 'Rose Quartz Heart Set', price: 899.0, originalPrice: 1399.0, category: 'healing-gifts', image: IMG.roseQuartz, badge: null, description: 'A beautifully packaged set of two polished rose quartz hearts in complementary pale pink hues, each approximately 4cm wide. Rose quartz is the stone of unconditional love and is associated with the heart chakra. It encourages self-love, attracts romantic partnerships, and fosters compassion. A meaningful gift for loved ones.' },
  { title: 'Amethyst Cluster', price: 1999.0, originalPrice: 2999.0, category: 'healing-gifts', image: IMG.blackStone, badge: null, description: 'A naturally formed amethyst cluster with deep violet points, weighing between 250–350g. Amethyst is known as the stone of peace and is said to calm an overactive mind, support restful sleep, and enhance intuition. Place it on a bedside table or meditation space. Each cluster is one-of-a-kind in shape and formation.' },
  { title: 'Black Tourmaline Protection Set', price: 1299.0, originalPrice: 1899.0, category: 'healing-gifts', image: IMG.blackStone, badge: null, description: 'Contains four medium-sized raw black tourmaline stones intended for placement in the four corners of a room to create a protective energy grid. Black tourmaline is considered one of the most powerful protective crystals, known to block electromagnetic radiation and repel negative psychic energy. Comes with placement and activation instructions.' },

  // Jap Mala - Karungali
  { title: 'Karungali Mala 108 Beads', price: 599.0, originalPrice: 999.0, category: 'mala-karungali', image: IMG.sandalwood, badge: null, description: 'A classic 108-bead Karungali (Black Ebony) japa mala, hand-strung on sturdy silk thread with a traditional tassel finish. Karungali wood is prized in Tamil Shaiva tradition for its density and natural black colour. It is believed to remove obstacles and negative influences, making it an excellent choice for daily mantra practice.' },
  { title: 'Silver Capped Karungali Mala', price: 899.0, originalPrice: 1499.0, category: 'mala-karungali', image: IMG.rudraksha, badge: null, description: 'Each of the 108 Karungali beads is individually capped with a thin layer of 92.5% sterling silver, creating a striking contrast between the deep black wood and bright silver. The combination is both aesthetically striking and spiritually significant, combining the protective energy of Karungali with the purifying lunar energy of silver. Anti-allergic.' },
  { title: 'Karungali Bracelet Set', price: 499.0, originalPrice: 799.0, category: 'mala-karungali', image: IMG.sandalwood, badge: null, description: 'A set of two stackable Karungali wood bracelets, each comprising 27 small beads (1/4 mala). Made with elastic cord for a comfortable fit on most wrist sizes. These can be worn alone or together. Each bead is machine polished and lightly oiled for a smooth, comfortable feel. One size fits most adults.' },
  { title: 'Premium Karungali Combo', price: 1199.0, originalPrice: 1999.0, category: 'mala-karungali', image: IMG.rudraksha, badge: null, description: 'Our best-value Karungali combo includes a full 108-bead mala, a matching 27-bead bracelet, and a small Karungali guru bead pendant on a black cord. All three pieces are made from the same batch of aged Karungali wood ensuring uniform colour and density. Presented in a satin gift pouch.' },

  // Jap Mala - Sandalwood
  { title: 'Sandalwood Mala 108 Beads', price: 799.0, originalPrice: 1299.0, category: 'mala-sandalwood', image: IMG.sandalwood, badge: null, description: 'Crafted from aromatic white sandalwood (Chandan), this 108-bead mala retains its natural fragrance for years. Sandalwood is sacred to Lord Vishnu and Goddess Lakshmi and is used in most Hindu and Buddhist japa practices. Its cooling and grounding aroma naturally aids concentration during meditation. Each bead is 8mm in diameter.' },
  { title: 'Premium Sandalwood Mala', price: 1499.0, originalPrice: 2299.0, category: 'mala-sandalwood', image: IMG.sandalwood, badge: null, description: 'A higher-grade sandalwood mala crafted from aged Mysore sandalwood — renowned for its superior fragrance and oil content. The beads (10mm) are hand-rounded and polished to a smooth satin finish. Strung on double-knotted silk thread for durability. A gift-worthy piece that comes in a premium wooden box.' },
  { title: 'Sandalwood Wrist Mala', price: 599.0, originalPrice: 999.0, category: 'mala-sandalwood', image: IMG.sandalwood, badge: null, description: 'A compact 27-bead sandalwood wrist mala that can be worn daily and used for counting shorter japa sets. The 6mm beads are smooth and lightweight, making this bracelet comfortable enough to forget you are wearing it. The natural sandalwood releases a gentle fragrance throughout the day, keeping you calm and centred.' },
  { title: 'Mysore Sandalwood Mala', price: 2499.0, originalPrice: 3999.0, category: 'mala-sandalwood', image: IMG.rudraksha, badge: null, description: 'The finest in our sandalwood range, crafted from old-growth Mysore sandalwood that is increasingly rare. The 12mm beads are deeply fragrant and hand-carved with a natural grain pattern. This mala is also believed to have powerful cooling and calming properties for the mind. Certificate of authenticity included.' },

  // Jap Mala - Rudraksha
  { title: 'Rudraksha Mala 5 Mukhi', price: 899.0, originalPrice: 1499.0, category: 'mala-rudraksha', image: IMG.rudraksha, badge: null, description: 'A traditional 108-bead mala made from certified 5 Mukhi (five-faced) Rudraksha. The 5 Mukhi symbolises the five elements and the five aspects of Lord Shiva. It is believed to bestow peace of mind, clarity, and good health. Beads are a consistent 6–7mm in size, naturally dried and unvarnished. String: waxed cotton thread.' },
  { title: 'Premium Rudraksha Mala', price: 1999.0, originalPrice: 2999.0, category: 'mala-rudraksha', image: IMG.rudraksha, badge: null, description: 'Combines a variety of mukhi — 5, 7, and 11 — in a single 108-bead mala for balanced spiritual benefits. Larger 8–9mm beads with well-defined natural mukhis. All beads are tested and certified by our gemologist. Strung on red silk thread with a gold-plated guru bead. Energised by puja before shipping.' },
  { title: 'Rudraksha Bracelet', price: 699.0, originalPrice: 1099.0, category: 'mala-rudraksha', image: IMG.sandalwood, badge: null, description: 'A sturdy 27-bead Rudraksha bracelet on strong elastic cord. Suitable for men and women, it can be worn on the right wrist (for sadhana) or the left (for general wellbeing). The natural Rudraksha beads are lightly cleaned and oiled — no artificial coatings. One size fits most wrists; M/L and XL options available on request.' },
  { title: 'Gauri Shankar Rudraksha', price: 3499.0, originalPrice: 4999.0, category: 'mala-rudraksha', image: IMG.rudraksha, badge: null, description: 'One of the rarest forms of Rudraksha, the Gauri Shankar is a naturally joined pair of two Rudraksha beads representing the divine union of Shiva (Shankar) and Parvati (Gauri). It is considered extremely auspicious for marital harmony, attracting a life partner, and family peace. Lab-certified and energised. Comes with a puja kit.' },

  // Daily Puja - Incense
  { title: 'Sandalwood Incense Sticks', price: 199.0, originalPrice: 299.0, category: 'puja-incense', image: IMG.incense, badge: null, description: 'Made using real sandalwood powder and natural binding agents — no charcoal, no synthetic fragrance. Each box contains 20 hand-rolled sticks with a burn time of approximately 45 minutes each. The clean, sweet smoke of sandalwood is traditionally used to purify the atmosphere and prepare the mind for prayer and meditation.' },
  { title: 'Mogra Agarbatti Box', price: 249.0, originalPrice: 399.0, category: 'puja-incense', image: IMG.incense, badge: null, description: 'Mogra (Arabian Jasmine) agarbatti made with real mogra extract blended into a masala base — not a synthetic fragrance spray. The result is a rich, floral aroma that fills the room without being overpowering. Each box contains 25 sticks with a burn time of approximately 30 minutes each. Free from toxic additives.' },
  { title: 'Premium Incense Collection', price: 599.0, originalPrice: 899.0, category: 'puja-incense', image: IMG.pujaCeremony, badge: null, description: 'A sampler gift box containing 6 varieties: Sandalwood, Mogra, Rose, Oud, Loban, and Guggal. Each variety has 10 hand-rolled sticks in its own labelled sleeve. This collection covers the full spectrum of traditional Indian puja fragrances. An ideal Diwali or housewarming gift for any devotee.' },
  { title: 'Temple Grade Dhoop Sticks', price: 399.0, originalPrice: 599.0, category: 'puja-incense', image: IMG.incense, badge: null, description: 'Thick, bamboless dhoop sticks made using the same formulation used in major South Indian temples — a blend of guggal, camphor, sandal, and havan samagri. Burn time is 60–90 minutes per stick. The dense, sacred smoke is especially suited for homa, yagna, and large puja ceremonies. Box of 12 sticks.' },

  // Daily Puja - Puja Samagri
  { title: 'Complete Puja Kit', price: 799.0, originalPrice: 1199.0, category: 'puja-samagri', image: IMG.pujaThali, badge: null, description: 'Everything you need to perform a full Satyanarayan or Griha Pravesh puja in one box. Contains: kumkum, haldi, chandan, roli, akshat (whole rice), camphor tablets, cotton wicks, a small brass diya, and incense sticks. All items are pure and free from adulteration. Includes a step-by-step puja guide in English and Hindi.' },
  { title: 'Havan Samagri Premium', price: 299.0, originalPrice: 499.0, category: 'puja-samagri', image: IMG.pujaCeremony, badge: null, description: 'A 500g pack of hand-blended havan samagri made from over 40 Ayurvedic herbs, roots, and resins including guggal, til, jau, kapoor kachri, and nagarmotha. Free from synthetic dyes and chemical binders. When offered in a homa fire, these materials produce purifying smoke that is believed to remove negativity and invoke divine energy.' },
  { title: 'Kumkum Haldi Set', price: 199.0, originalPrice: 299.0, category: 'puja-samagri', image: IMG.pujaThali, badge: null, description: 'A matching pair of small brass containers (dibbi) filled with pure natural kumkum (vermillion) and raw haldi (turmeric) powder. Both are essential for most Hindu pujas and are traditionally offered to the deity. The kumkum is made from turmeric and slaked lime — no synthetic dyes. The haldi is sourced from Erode, Tamil Nadu.' },
  { title: 'Pooja Thali Complete Set', price: 1299.0, originalPrice: 1899.0, category: 'puja-samagri', image: IMG.pujaThali, badge: null, description: 'A solid brass pooja thali (28cm diameter) with five integral compartments for diya, kumkum, akshat, flowers, and camphor. Comes pre-filled with a starter set of puja samagri and a ghee diya. The thali\'s thick-gauge brass construction makes it heirloom-quality — designed to last for generations. Polished to a mirror finish.' },

  // Daily Puja - Ghee Wicks
  { title: 'Pure Cow Ghee Wicks', price: 149.0, originalPrice: 249.0, category: 'puja-wicks', image: IMG.gheelamp, badge: null, description: 'Hand-rolled wicks made from 100% pure cow\'s-milk ghee, shaped into ready-to-use cylindrical forms. These wicks burn for 4–6 hours without smoke or odour, producing a calm, steady flame. Traditionally used for Aarti and overnight diyas. Pack of 50 wicks. Pure ghee wicks are considered the highest quality offering in Vedic tradition.' },
  { title: 'Cotton Wicks Bundle', price: 99.0, originalPrice: 149.0, category: 'puja-wicks', image: IMG.diwaliLamps, badge: null, description: 'Natural unbleached cotton wicks, hand-twisted into a flat braid for even oil absorption. Suitable for all types of diyas — brass, clay, or glass — and compatible with sesame oil, coconut oil, or ghee. Each wick burns cleanly for 2–3 hours. Bundle contains 100 wicks in a resealable pouch. Free from synthetic fibres.' },
  { title: 'Long Burning Ghee Wicks', price: 249.0, originalPrice: 399.0, category: 'puja-wicks', image: IMG.gheelamp, badge: null, description: 'Extended-burn version of our pure ghee wicks, moulded into a larger cylindrical form (approx 5cm tall). Burns continuously for 8–10 hours, making them ideal for Akhand Diya (continuous flame kept burning for 24–48 hours for auspicious occasions). Each pack contains 24 wicks. No trimming or repositioning needed.' },
  { title: 'Premium Diya Wicks Set', price: 199.0, originalPrice: 299.0, category: 'puja-wicks', image: IMG.brassDiya, badge: null, description: 'A mixed set of both ghee wicks and cotton wicks — 25 of each — giving you the flexibility to use whichever is appropriate for the occasion. Comes with a small brass wick holder (deepam stand) that keeps wicks upright in any diya. A practical everyday puja essential for any devout household.' },

  // High Ticket Brass Idols
  { title: 'Tirupati Balaji Brass Idol - 30 Inch', price: 24999.0, originalPrice: 34999.0, category: 'brass-idols', image: IMG.brassIdol, badge: null, description: 'A majestic 30-inch hand-cast brass idol of Lord Venkateswara (Tirupati Balaji) finished with a dark antiqued patina and gold-leaf highlights on the crown and ornaments. Made by master sculptors in Swamimalai, Tamil Nadu — a village with a 1,000-year tradition of Panchaloha and brass idol casting. Supplied with a wooden pedestal and care kit.' },
  { title: 'Nataraja Brass Statue - 51 Inch', price: 49999.0, originalPrice: 69999.0, category: 'brass-idols', image: IMG.brassIdol, badge: null, description: 'A museum-quality 51-inch Nataraja cast from 80% pure brass using the centuries-old lost-wax (cire perdue) technique. The celestial ring of fire (prabhamandala), the lifted leg, and every individual flame are exquisitely detailed. A landmark statement piece for temples, corporate spaces, or palatial homes. Custom sizing available on enquiry.' },
  { title: 'Lakshmi Ganesh Set - 24 Inch', price: 19999.0, originalPrice: 29999.0, category: 'brass-idols', image: IMG.ganesh, badge: null, description: 'The most auspicious pairing in Hindu worship — Goddess Lakshmi and Lord Ganesha — cast together as a matching set, each 24 inches tall. Seated posture, intricate jewellery, and fine facial features are all hand-carved after casting. Traditionally worshipped together during Diwali and Dhan Trayodashi. Heavy-duty wooden bases included.' },
  { title: 'Radha Krishna Brass Idol - 36 Inch', price: 34999.0, originalPrice: 49999.0, category: 'brass-idols', image: IMG.brassIdol, badge: null, description: 'A breathtaking 36-inch brass depiction of Radha and Krishna in the Yugal Swaroop (divine couple) pose. Krishna plays his flute while Radha listens in adoration. The idol is hand-painted with natural mineral pigments to highlight the garments and jewellery. Cast by fourth-generation idol-makers in Vrindavan. A centrepiece for any mandir or devotional space.' },
];

const prisma = new PrismaClient();

async function main() {
  console.log('Clearing old product database...');
  await prisma.review.deleteMany({});
  await prisma.orderItem.deleteMany({});
  await prisma.product.deleteMany({});

  console.log('Seeding database with descriptions...');
  for (const product of products) {
    await prisma.product.create({
        data: product
    });
  }
  console.log('Database seeded successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
